# -*- coding: utf-8 -*-
"""Generate overlay/src/embedded_payload.h from mustcode_asm.build() + CORE_HOOKS.

Assembles MustCode at two base sets and emits a reloc table so the DLL can
VirtualAlloc anywhere and patch absolute addresses at runtime.
"""
from __future__ import print_function

import os
import struct
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, ROOT)

from payload import (  # noqa: E402
    ASM_TEXT, SYMBOLS, LABELS, CORE_HOOKS, EP1_CORE_HOOKS,
)
from mustcode_asm import build  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'embedded_payload.h')

# Two distinct non-overlapping base sets (MOD stays 0x400000 — RA3 has no ASLR).
SET_A = dict(mc=0x51000000, mc2=0x51003000, flags=0x51004000, idb=0x51004100, mod=0x400000)
SET_B = dict(mc=0x52000000, mc2=0x52003000, flags=0x52004000, idb=0x52004100, mod=0x400000)

SYM_MC, SYM_MC2, SYM_FLAGS, SYM_IDB = 0, 1, 2, 3


def classify(val_a, val_b):
    """Return (sym_id, addend) if this dword is a relocatable absolute, else None."""
    pairs = [
        (SYM_MC, SET_A['mc'], SET_B['mc']),
        (SYM_MC2, SET_A['mc2'], SET_B['mc2']),
        (SYM_FLAGS, SET_A['flags'], SET_B['flags']),
        (SYM_IDB, SET_A['idb'], SET_B['idb']),
    ]
    for sid, ba, bb in pairs:
        if val_b - val_a == bb - ba:
            addend = val_a - ba
            # Reasonable addend window for our segments
            if -0x10000 <= addend <= 0x10000:
                # Verify consistency
                if val_a == ba + addend and val_b == bb + addend:
                    return sid, addend
    return None


def find_relocs(blob_a, blob_b):
    assert len(blob_a) == len(blob_b)
    relocs = []
    i = 0
    n = len(blob_a)
    while i + 4 <= n:
        va = struct.unpack_from('<I', blob_a, i)[0]
        vb = struct.unpack_from('<I', blob_b, i)[0]
        if va != vb:
            hit = classify(va, vb)
            if hit:
                relocs.append((i, hit[0], hit[1]))
                i += 4
                continue
        i += 1
    return relocs


def c_bytes(data, name):
    lines = ['static const unsigned char %s[%d] = {' % (name, len(data))]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append('  ' + ', '.join('0x%02X' % b for b in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    mc_a, mc2_a = build(ASM_TEXT, SYMBOLS, SET_A['mc'], SET_A['mc2'],
                        SET_A['flags'], SET_A['idb'], SET_A['mod'])
    mc_b, mc2_b = build(ASM_TEXT, SYMBOLS, SET_B['mc'], SET_B['mc2'],
                        SET_B['flags'], SET_B['idb'], SET_B['mod'])
    assert len(mc_a) == len(mc_b) and len(mc2_a) == len(mc2_b)

    rel_mc = find_relocs(mc_a, mc_b)
    rel_mc2 = find_relocs(mc2_a, mc2_b)
    print('MC size=%d relocs=%d; MC2 size=%d relocs=%d' % (
        len(mc_a), len(rel_mc), len(mc2_a), len(rel_mc2)))

    # Label offsets for hooks (mc_xxx)
    def hook_lines(hooks):
        out = []
        for name, va, aob, target_off in hooks:
            tag = 'mc_' + format(target_off, 'x')
            off = LABELS['MC'].get(tag)
            if off is None:
                raise SystemExit('missing label %s for %s' % (tag, name))
            aob_bytes = bytes.fromhex(aob)
            out.append(
                '  {"%s", 0x%X, %d, %d, {%s}},' % (
                    name, va, off, len(aob_bytes),
                    ', '.join('0x%02X' % b for b in aob_bytes) +
                    (', 0' * (16 - len(aob_bytes)))  # pad to 16
                )
            )
        return out

    label_lines = hook_lines(CORE_HOOKS)
    label_lines_ep1 = hook_lines(EP1_CORE_HOOKS)

    parts = []
    parts.append('// Auto-generated by overlay/tools/gen_overlay_payload.py — do not edit.')
    parts.append('#pragma once')
    parts.append('#include <stdint.h>')
    parts.append('')
    parts.append('enum OverlayRelocSym { kRelMc = 0, kRelMc2 = 1, kRelFlags = 2, kRelIdb = 3 };')
    parts.append('struct OverlayReloc { uint32_t offset; uint8_t sym; int32_t addend; };')
    parts.append('struct OverlayHookDef {')
    parts.append('  const char* name;')
    parts.append('  uint32_t hook_va;   // absolute VA including 0x400000')
    parts.append('  uint32_t mc_label;  // offset into MustCode')
    parts.append('  uint8_t aob_len;')
    parts.append('  uint8_t aob[16];')
    parts.append('};')
    parts.append('')
    parts.append(c_bytes(mc_a, 'kEmbeddedMc'))
    parts.append('')
    parts.append(c_bytes(mc2_a, 'kEmbeddedMc2'))
    parts.append('')
    parts.append('static const OverlayReloc kMcRelocs[] = {')
    for off, sid, add in rel_mc:
        parts.append('  {%u, %u, %d},' % (off, sid, add))
    parts.append('};')
    parts.append('static const OverlayReloc kMc2Relocs[] = {')
    for off, sid, add in rel_mc2:
        parts.append('  {%u, %u, %d},' % (off, sid, add))
    parts.append('};')
    parts.append('')
    parts.append('static const OverlayHookDef kOverlayHooks[] = {')
    parts.extend(label_lines)
    parts.append('};')
    parts.append('static const int kOverlayHookCount = %d;' % len(CORE_HOOKS))
    parts.append('')
    parts.append('// ra3ep1_1.0.game. OreMine has no unique site yet.')
    parts.append('static const OverlayHookDef kOverlayHooksEp1[] = {')
    parts.extend(label_lines_ep1)
    parts.append('};')
    parts.append('static const int kOverlayHookEp1Count = %d;' % len(EP1_CORE_HOOKS))
    parts.append('')
    parts.append('static const char* kPlayerHookNames[] = {')
    for n in ('PlayerID', 'Money', 'Power', 'SCPoint', 'HaveAllSC'):
        parts.append('  "%s",' % n)
    parts.append('};')
    parts.append('static const int kPlayerHookNameCount = 5;')
    parts.append('')

    text = '\n'.join(parts) + '\n'
    out_path = os.path.normpath(OUT)
    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('Wrote', out_path, 'bytes', len(text))


if __name__ == '__main__':
    main()
