#pragma once
// Official SAGE GameObject ids -> Chinese display names (RA3).
// Source ids match XML GameObject id= / CSF Name:<id>, NOT popular English nicknames.
// Synced with repo-root unit_names.txt (player-verified names take priority in file).

struct UnitNameEntry {
  const char* id;
  const char* zh;
};

static const UnitNameEntry kUnitNamesZh[] = {
    // ---- Soviet units ----
    {"SovietScoutInfantry", u8"战熊"},
    {"SovietAntiInfantryInfantry", u8"征召兵"},
    {"SovietAntiVehicleInfantry", u8"防空部队"},
    {"SovietAntiAirInfantry", u8"防空步兵"},
    {"SovietEngineer", u8"工程师"},
    {"SovietCommando", u8"娜塔莎"},
    {"SovietCommandoTech1", u8"娜塔莎"},
    {"SovietAntiInfantryVehicle", u8"镰刀机甲"},
    {"SovietAntiAirVehicleTech1", u8"牛蛙步行机甲"},
    {"SovietAntiVehicleVehicleTech1", u8"铁锤坦克"},
    {"SovietAntiVehicleVehicleTech2", u8"磁暴坦克"},
    {"SovietAntiVehicleVehicleTech3", u8"天启坦克"},
    {"SovietAntiStructureVehicle", u8"V4火箭发射车"},
    {"SovietAntiGroundAircraft", u8"双刃直升机"},
    {"SovietBomberAircraft", u8"基洛夫飞艇"},
    {"SovietFighterAircraft", u8"米格战机"},
    {"SovietAntiNavyShipTech1", u8"磁暴快艇"},
    {"SovietAntiNavyShipTech2", u8"阿库拉潜艇"},
    {"SovietSubmarine", u8"阿库拉潜艇"},  // alias; CSF id is AntiNavyShipTech2
    {"SovietAntiAirShip", u8"牛蛙载具"},
    {"SovietAntiAirShip_Ground", u8"牛蛙载具"},
    {"SovietAntiStructureShip", u8"无畏战舰"},
    {"SovietMiner", u8"苏联矿车"},
    {"SovietMiner_Naval", u8"苏联矿车"},
    {"SovietMCV", u8"MCV"},
    {"SovietMCV_Naval", u8"MCV"},
    {"SovietSurveyor", u8"史普尼克勘察车"},
    {"SovietSurveyor_Naval", u8"史普尼克勘察车"},
    {"SovietScoutVehicle", u8"恐怖机器人"},
    {"SovietHeavyAntiVehicleInfantry", u8"磁暴步兵"},

    // ---- Allied units ----
    {"AlliedScoutInfantry", u8"警犬"},
    {"AlliedAntiInfantryInfantry", u8"维和步兵"},
    {"AlliedAntiVehicleInfantry", u8"标枪兵"},
    {"AlliedAntiAirInfantry", u8"标枪兵"},
    {"AlliedEngineer", u8"工程师"},
    {"AlliedInfiltrationInfantry", u8"间谍"},
    {"AlliedCommando", u8"谭雅"},
    {"AlliedCommandoTech1", u8"谭雅"},
    {"AlliedAntiInfantryVehicle", u8"激流ACV"},
    {"AlliedAntiInfantryVehicle_Ground", u8"激流ACV"},
    {"AlliedInfantryVehicle", u8"多功能步兵车"},
    {"AlliedAntiVehicleVehicleTech1", u8"守护者坦克"},
    {"AlliedAntiVehiclevehicleTech1", u8"守护者坦克"},
    {"AlliedAntiVehicleVehicleTech3", u8"幻影坦克"},
    {"AlliedAntiStructureVehicle", u8"雅典娜炮"},
    {"AlliedAntiAirVehicleTech1", u8"多功能步兵车"},
    {"AlliedFighterAircraft", u8"阿波罗战斗机"},
    {"AlliedAntiGroundAircraft", u8"维和轰炸机"},
    {"AlliedBomberAircraft", u8"世纪轰炸机"},
    {"AlliedSupportAircraft", u8"冰冻直升机"},
    {"AlliedAntiNavyShipTech1", u8"突袭驱逐舰"},
    {"AlliedAntiAirShip", u8"水翼船"},
    {"AlliedAntiStructureShip", u8"航空母舰"},
    {"AlliedMiner", u8"勘探者"},
    {"AlliedMiner_Naval", u8"勘探者"},
    {"AlliedMCV", u8"MCV"},
    {"AlliedMCV_Naval", u8"MCV"},
    {"AlliedSurveyor", u8"勘探者"},

    // ---- Japan / Empire units ----
    {"JapanAntiInfantryInfantry", u8"帝国武士"},
    {"JapanAntiVehicleInfantry", u8"坦克杀手"},
    {"JapanInfiltrationInfantry", u8"忍者"},
    {"JapanAntiAirInfantry", u8"火箭天使"},  // common alias
    {"JapanAntiVehicleInfantryTech3", u8"火箭天使"},
    {"JapanEngineer", u8"工程师"},
    {"JapanCommando", u8"由纪"},
    {"JapanCommandoTech1", u8"奥米加百合子"},
    {"JapanScoutInfantry", u8"爆裂机器人"},
    {"JapanAntiInfantryVehicle", u8"天狗机器人"},
    {"JapanAntiInfantryVehicleTech1", u8"天狗机甲"},
    {"JapanLightTransportVehicle", u8"迅雷运输车"},
    {"JapanAntiVehicleVehicleTech1", u8"海啸坦克"},
    {"JapanAntiVehicleVehicleTech1_Naval", u8"海啸坦克"},
    {"JapanAntiAirVehicleTech1", u8"打击者-VX"},
    {"JapanAntiVehicleVehicle", u8"鬼王"},
    {"JapanMechaKing", u8"将军刽子手"},
    {"JapanAntiStructureVehicle", u8"波能坦克"},
    {"JapanAntiShipAircraft", u8"天狗战机"},
    {"JapanFinalSquadronAircraft", u8"斩首中队"},
    {"JapanNavyScoutShip", u8"迷你潜艇"},
    {"JapanAntiAirShip", u8"海翼"},
    {"JapanAntiStructureShip", u8"将军战列舰"},
    {"JapanAntiVehicleShip", u8"薙刀巡洋舰"},
    {"JapanMiner", u8"采矿车"},
    {"JapanMiner_Naval", u8"采矿车"},
    {"JapanMCV", u8"MCV"},
    {"JapanMCV_Naval", u8"MCV"},
    {"JapanSurveyor", u8"勘探者"},
    {"JapanPointDefenseDrone", u8"点防御无人机"},

    // ---- Buildings: Soviet ----
    {"SovietConstructionYard", u8"建筑工厂"},
    {"SovietConYard", u8"建造场"},
    {"SovietPowerPlant", u8"反应炉"},
    {"SovietPowerPlantAdvanced", u8"超级反应炉"},
    {"SovietPowerPlantAdv", u8"超级反应炉"},
    {"SovietRefinery", u8"矿石精炼厂"},
    {"SovietBarracks", u8"军营"},
    {"SovietWarFactory", u8"战争工厂"},
    {"SovietNavalYard", u8"海军船坞"},
    {"SovietShipyard", u8"海军船坞"},
    {"SovietAirfield", u8"机场"},
    {"SovietCrane", u8"起重机"},
    {"SovietOutpost", u8"前哨站"},
    {"SovietBunker", u8"战斗碉堡"},
    {"SovietBaseDefenseGround", u8"哨枪"},
    {"SovietBaseDefenseAir", u8"防空炮"},
    {"SovietBaseDefenseAdvanced", u8"磁暴线圈"},
    {"SovietBaseDefenseAdv", u8"磁暴线圈"},
    {"SovietTeslaWallHub", u8"磁暴墙枢纽"},
    {"SovietTechStructure", u8"战斗研究所"},
    {"SovietIronCurtain", u8"铁幕装置"},
    {"SovietVacuumImploder", u8"真空内爆弹"},
    {"SovietSuperWeapon", u8"真空内爆弹"},
    {"SovietSuperWeaponAdvanced", u8"真空内爆弹"},

    // ---- Buildings: Allied ----
    {"AlliedConstructionYard", u8"建筑工厂"},
    {"AlliedConYard", u8"建造场"},
    {"AlliedPowerPlant", u8"发电厂"},
    {"AlliedRefinery", u8"矿石精炼厂"},
    {"AlliedBarracks", u8"新兵训练营"},
    {"AlliedWarFactory", u8"装甲工厂"},
    {"AlliedNavalYard", u8"海港"},
    {"AlliedShipyard", u8"海军船坞"},
    {"AlliedAirfield", u8"空军基地"},
    {"AlliedCrane", u8"起重机"},
    {"AlliedOutpost", u8"前哨站"},
    {"AlliedBaseDefense", u8"多功能步兵炮塔"},
    {"AlliedBaseDefenseAdvanced", u8"光谱塔"},
    {"AlliedWallHub", u8"围墙"},
    {"AlliedTechStructure", u8"科技中心"},
    {"AlliedChronosphere", u8"超时空传送仪"},
    {"AlliedProtonCollider", u8"质子撞击炮"},

    // ---- Buildings: Japan ----
    {"JapanConstructionYard", u8"建筑工厂"},
    {"JapanConYard", u8"建造场"},
    {"JapanPowerPlant", u8"瞬息发电机"},
    {"JapanRefinery", u8"矿石精炼厂"},
    {"JapanBarracks", u8"瞬息道场"},
    {"JapanWarFactory", u8"机甲工厂"},
    {"JapanNavalYard", u8"帝国码头"},
    {"JapanShipyard", u8"帝国船坞"},
    {"JapanCrane", u8"起重机"},
    {"JapanOutpost", u8"前哨站"},
    {"JapanBaseDefense", u8"防卫者-VX"},
    {"JapanBaseDefenseAdvanced", u8"波能塔"},
    {"JapanBaseDefenseAdv", u8"波力塔"},
    {"JapanWallHub", u8"围墙"},
    {"JapanTechStructure", u8"纳米科技电脑主机"},
    {"JapanPsionicDecimator", u8"超能波毁灭装置"},
    {"JapanSuperWeapon", u8"纳米虫群巢穴"},
    {"JAPANSUPERWEAPON", u8"纳米虫群巢穴"},
    {"JapanSuperWeaponAdvanced", u8"超能波毁灭装置"},
    {"JapanNanotechMainframe", u8"纳米主机"},

    // ---- Neutral / tech buildings ----
    {"HospitalTechBuilding", u8"医院"},
    {"HospitalTechStructure", u8"医院"},  // alias
    {"GarageTechStructure", u8"车库"},
    {"ObservationPostTechStructure", u8"监视哨"},
    {"OilDerrick", u8"油井"},
    {"OilDerrick_OnWater", u8"油井"},
    {"TechBuildingOilDerrick", u8"油井"},
    {"ShipYardTechStructure", u8"干船坞"},
    {"AirportTechStructure", u8"机场"},
    {"VeterancyTechStructure", u8"精兵学院"},
    {"DefensiveStructureTechStructure", u8"中立防御基地"},
    {"OreNode", u8"矿脉"},
    {"TechBuildingOreNode", u8"矿脉"},
    {"TechBuildingOreNode2", u8"双矿脉"},
    {"TechBuildingOreNode4", u8"四矿脉"},
    {"OreNode2a", u8"矿脉"},
    {"OreNode2b", u8"矿脉"},
    {"OreNode4a", u8"矿脉"},
    {"OreNode4b", u8"矿脉"},
    {"OreNode4c", u8"矿脉"},
    {"OreNode4d", u8"矿脉"},
    {"CreateHealMP", u8"治疗箱"},
    {"CreateMoneyMP", u8"资金箱"},
};
